server:
  port: 8989
spring:
  application:
    name: gcloud-turbine
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
turbine:
  cluster-name-expression: new String("default")
  app-config: gcloud-oauth2,gcloud-service1,gcloud-service2