server:
  port: 8989
spring:
  application:
    name: gcloud-turbine
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    hostname: ${DOCKER_HOSTNAME:localhost}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_URL:localhost:8761}/eureka/
turbine:
  cluster-name-expression: new String("default")
  app-config: gcloud-oauth2,gcloud-service1,gcloud-service2,gcloud-service3