server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/grekier/cloud-config
          proxy:
            http:
              host: localhost
              port: 5865
            https:
              host: localhost
              port: 5865
  application:
    name: configserver
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    org.springframework.cloud.config.server: DEBUG