server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/grekier/cloud-config
  application:
    name: configserver
management:
  endpoints:
    web:
      exposure:
        include: "*"