spring:
  zipkin:
    base-url: http://${ZIPKIN_SERVICE_URL:localhost:9411}
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: gateway
server:
  port: 9000
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    hostname: ${DOCKER_HOSTNAME:localhost}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_URL:localhost:8761}/eureka/
logging:
  level:
    org.springframework.cloud: debug